version: "3"

services:
  paste-bin:
    container_name: paste-bin
    image: ghcr.io/enchant97/hasty-paste:latest
    restart: unless-stopped
    environment:
      - PASTE_ROOT=${PASTE_ROOT:-DC-UNDEFINED}
      - TIME_ZONE=${TIME_ZONE:-DC-UNDEFINED}
    volumes:
      - data:/app/data
    ports:
      - 8000:8000

volumes:
  data:
