version: "3"

services:
  paste_bin:
    container_name: paste-bin
    image: ghcr.io/enchant97/paste-bin:latest
    restart: unless-stopped
    volumes:
      - data:/app/data
    ports:
      - 8000:8000

volumes:
  data:
