site_name: Hasty Paste
site_url: https://enchantedcode.co.uk/hasty-paste/
repo_url: https://github.com/enchant97/hasty-paste
use_directory_urls: false
copyright: Copyright © 2022 Leo Spratt under FDLv1.3-or-later
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
