name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, next ]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install hatch
    - name: Run Unit Tests
      run: mkdir reports && hatch run test:tests
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: reports
        path: reports/
